version: '3.8'

services:
  voting-app:
    image: vote-app
    networks:
      - frontend-ntw
    ports:
      - "5000:80"
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 3

  redis:
    image: redis:latest
    networks:
      - frontend-ntw
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 3

  worker:
    image: worker-app
    networks:
      - frontend-ntw
      - backend-ntw
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 3

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend-ntw
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 3
    volumes:
      - db-data:/var/lib/postgresql/data

  result:
    image: result-app
    networks:
      - backend-ntw
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 3
    ports:
      - "7000:80"
networks:
  frontend-ntw:
    driver: overlay
    external: true
  backend-ntw:
    driver: overlay
    external: true

volumes:
  db-data:
